-- =====================================================================
-- SlimBANK v2: своя авторизация без Supabase Auth (без писем и лимитов)
-- Выполнить целиком в SQL Editor. Можно запускать повторно.
-- =====================================================================
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- счета
create table if not exists public.accounts (
  id           bigint generated by default as identity primary key,
  login_id     text not null unique,
  phone        text,
  email        text,
  username     text,
  pass_hash    text not null,
  plan         text default 'basic',
  balance      numeric(40,2) default 0,
  last_accrual bigint default 0,
  state        jsonb default '{}'::jsonb,
  token        uuid,
  token_exp    timestamptz,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

create unique index if not exists accounts_username_uniq
  on public.accounts (lower(username)) where username is not null;
create index if not exists accounts_token_idx on public.accounts (token);
create index if not exists accounts_balance_idx on public.accounts (balance desc);

-- таблица закрыта напрямую: всё только через функции ниже
alter table public.accounts enable row level security;
revoke all on table public.accounts from anon, authenticated;

-- ---------------------------------------------------------------- тарифы
create table if not exists public.plans2 (
  code    text primary key,
  accrual numeric(20,2) not null
);
insert into public.plans2 (code, accrual) values
  ('basic', 25), ('plus', 90), ('platinum', 260), ('black', 900), ('infinite', 3200)
on conflict (code) do update set accrual = excluded.accrual;
revoke all on table public.plans2 from anon, authenticated;

-- ---------------------------------------------------------------- промокоды
create table if not exists public.promos2 (
  code     text primary key,
  money    numeric(40,2) default 0,
  gift     text,
  score    int,
  note     text,
  uses     int default 0,
  max_uses int
);

insert into public.promos2 (code, money, gift, score, note, max_uses) values
  ('WTHJW',     100000000000000000, null, null, '100 квадриллионов на баланс', null),
  ('SLIM2026',  500000,             null, null, 'Стартовый бонус',            null),
  ('LUCKY777',  7777777,            null, null, 'Счастливые семёрки',         null),
  ('GRAM888',   88888888,           null, null, 'Бонус GRAM',                null),
  ('BEARHUG',   0,                  'bear', null, 'Подарок: мишка',           null),
  ('CREDITFIX', 0,                  null, 90,   'Скоринг поднят до 90',       null)
on conflict (code) do update
  set money = excluded.money, gift = excluded.gift,
      score = excluded.score, note = excluded.note;

create table if not exists public.promo_uses (
  account_id bigint not null references public.accounts(id) on delete cascade,
  code       text   not null,
  used_at    timestamptz default now(),
  primary key (account_id, code)
);

revoke all on table public.promos2, public.promo_uses from anon, authenticated;

-- =====================================================================
-- ВНУТРЕННИЕ ФУНКЦИИ
-- =====================================================================
create or replace function public._acc(p_token uuid)
returns bigint language sql security definer set search_path = public as $$
  select id from public.accounts
   where token = p_token and (token_exp is null or token_exp > now());
$$;
revoke all on function public._acc(uuid) from anon, authenticated;

create or replace function public._norm(p text)
returns text language sql immutable as $$
  select regexp_replace(coalesce(p, ''), '\D', '', 'g');
$$;

create or replace function public._newtoken(p_id bigint)
returns uuid language plpgsql security definer set search_path = public as $$
declare t uuid;
begin
  t := gen_random_uuid();
  update public.accounts
     set token = t, token_exp = now() + interval '180 days', updated_at = now()
   where id = p_id;
  return t;
end;
$$;
revoke all on function public._newtoken(bigint) from anon, authenticated;

create or replace function public._payload(p_id bigint)
returns jsonb language sql security definer set search_path = public as $$
  select jsonb_build_object(
           'ok', true,
           'login_id', a.login_id,
           'balance', a.balance,
           'plan', a.plan,
           'username', a.username,
           'last_accrual', a.last_accrual,
           'state', coalesce(a.state, '{}'::jsonb)
         )
    from public.accounts a where a.id = p_id;
$$;
revoke all on function public._payload(bigint) from anon, authenticated;

-- =====================================================================
-- РЕГИСТРАЦИЯ / ВХОД
-- =====================================================================
create or replace function public.sb_register(p_login text, p_pass text, p_state jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_login text := public._norm(p_login);
  v_id    bigint;
  v_hash  text;
  v_bal   numeric;
begin
  if length(v_login) < 5 then return jsonb_build_object('ok', false, 'error', 'bad_login'); end if;
  if length(coalesce(p_pass, '')) < 4 then return jsonb_build_object('ok', false, 'error', 'weak'); end if;

  select id, pass_hash into v_id, v_hash from public.accounts where login_id = v_login;

  if v_id is not null then
    -- аккаунт есть: пускаем только с верным паролем
    if v_hash = crypt(p_pass, v_hash) then
      return public._payload(v_id) || jsonb_build_object('token', public._newtoken(v_id), 'existed', true);
    end if;
    return jsonb_build_object('ok', false, 'error', 'exists');
  end if;

  v_bal := coalesce((p_state->>'balance')::numeric, 0);

  insert into public.accounts (login_id, phone, email, pass_hash, plan, balance, last_accrual, state)
  values (
    v_login,
    p_state->>'phone',
    p_state->>'email',
    crypt(p_pass, gen_salt('bf')),
    coalesce(p_state->>'plan', 'basic'),
    v_bal,
    coalesce((p_state->>'lastAccrual')::bigint, 0),
    coalesce(p_state, '{}'::jsonb)
  )
  returning id into v_id;

  return public._payload(v_id) || jsonb_build_object('token', public._newtoken(v_id), 'created', true);
end;
$$;

create or replace function public.sb_login(p_login text, p_pass text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_raw   text := lower(trim(coalesce(p_login, '')));
  v_digit text := public._norm(p_login);
  v_id    bigint;
  v_hash  text;
begin
  select id, pass_hash into v_id, v_hash
    from public.accounts
   where (length(v_digit) >= 5 and (login_id = v_digit or public._norm(phone) = v_digit))
      or lower(email) = v_raw
      or lower(username) = ltrim(v_raw, '@')
   limit 1;

  if v_id is null then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
  if v_hash <> crypt(coalesce(p_pass, ''), v_hash) then
    return jsonb_build_object('ok', false, 'error', 'bad_pass');
  end if;

  return public._payload(v_id) || jsonb_build_object('token', public._newtoken(v_id));
end;
$$;

-- =====================================================================
-- СОСТОЯНИЕ СЧЕТА
-- =====================================================================
create or replace function public.sb_pull(p_token uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_id bigint := public._acc(p_token);
begin
  if v_id is null then return jsonb_build_object('ok', false, 'error', 'no_session'); end if;
  return public._payload(v_id);
end;
$$;

create or replace function public.sb_push(p_token uuid, p_state jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_id   bigint := public._acc(p_token);
  v_name text;
  v_st   jsonb;
begin
  if v_id is null then return jsonb_build_object('ok', false, 'error', 'no_session'); end if;

  -- юзернейм хранит сервер: клиент не может его подменить
  select username into v_name from public.accounts where id = v_id;
  v_st := coalesce(p_state, '{}'::jsonb);
  if v_name is not null then
    v_st := jsonb_set(v_st, '{username}', to_jsonb(v_name), true);
  else
    v_st := v_st - 'username';
  end if;

  update public.accounts
     set state        = v_st,
         balance      = coalesce((v_st->>'balance')::numeric, balance),
         plan         = coalesce(v_st->>'plan', plan),
         last_accrual = coalesce((v_st->>'lastAccrual')::bigint, last_accrual),
         phone        = coalesce(v_st->>'phone', phone),
         email        = coalesce(v_st->>'email', email),
         updated_at   = now()
   where id = v_id;

  return jsonb_build_object('ok', true);
end;
$$;

-- =====================================================================
-- НАЧИСЛЕНИЯ ПО ТАРИФУ (честное время сервера)
-- =====================================================================
create or replace function public.sb_claim_accruals(p_token uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_id     bigint := public._acc(p_token);
  v_now    bigint := (extract(epoch from now()) * 1000)::bigint;
  v_last   bigint;
  v_plan   text;
  v_rate   numeric;
  v_period bigint := 600000;
  v_ticks  int;
  v_add    numeric;
begin
  if v_id is null then return jsonb_build_object('ok', false, 'error', 'no_session'); end if;

  select last_accrual, plan into v_last, v_plan from public.accounts where id = v_id;
  if v_last is null or v_last = 0 then
    update public.accounts set last_accrual = v_now where id = v_id;
    return jsonb_build_object('ok', true, 'added', 0);
  end if;

  select accrual into v_rate from public.plans2 where code = coalesce(v_plan, 'basic');
  v_rate  := coalesce(v_rate, 25);
  v_ticks := least(floor((v_now - v_last) / v_period)::int, 288);
  if v_ticks <= 0 then return jsonb_build_object('ok', true, 'added', 0); end if;

  v_add := v_rate * v_ticks;

  update public.accounts
     set balance      = balance + v_add,
         last_accrual = v_last + v_ticks::bigint * v_period,
         state        = jsonb_set(
                          jsonb_set(coalesce(state, '{}'::jsonb), '{balance}',
                                    to_jsonb(balance + v_add), true),
                          '{lastAccrual}', to_jsonb(v_last + v_ticks::bigint * v_period), true),
         updated_at   = now()
   where id = v_id;

  return jsonb_build_object('ok', true, 'added', v_add, 'ticks', v_ticks);
end;
$$;

-- =====================================================================
-- ЮЗЕРНЕЙМЫ (общие для всех игроков)
-- =====================================================================
create or replace function public.sb_username_free(p_name text)
returns boolean language plpgsql security definer set search_path = public as $$
declare v text := ltrim(lower(trim(coalesce(p_name, ''))), '@');
begin
  if v !~ '^[a-z0-9_]{4,20}$' then return false; end if;
  return not exists (select 1 from public.accounts where lower(username) = v);
end;
$$;

create or replace function public.sb_claim_username(p_token uuid, p_name text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_id bigint := public._acc(p_token);
  v    text   := ltrim(trim(coalesce(p_name, '')), '@');
begin
  if v_id is null then return jsonb_build_object('ok', false, 'error', 'no_session'); end if;
  if lower(v) !~ '^[a-z0-9_]{4,20}$' then
    return jsonb_build_object('ok', false, 'error', 'bad_format');
  end if;
  if exists (select 1 from public.accounts where lower(username) = lower(v) and id <> v_id) then
    return jsonb_build_object('ok', false, 'error', 'taken');
  end if;

  update public.accounts
     set username   = v,
         state      = jsonb_set(coalesce(state, '{}'::jsonb), '{username}', to_jsonb(v), true),
         updated_at = now()
   where id = v_id;

  return jsonb_build_object('ok', true, 'username', v);
exception when unique_violation then
  return jsonb_build_object('ok', false, 'error', 'taken');
end;
$$;

-- =====================================================================
-- ПРОМОКОДЫ (один раз на аккаунт, проверяет сервер)
-- =====================================================================
create or replace function public.sb_redeem_promo(p_token uuid, p_code text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_id   bigint := public._acc(p_token);
  v_code text   := upper(trim(coalesce(p_code, '')));
  p      record;
begin
  if v_id is null then return jsonb_build_object('ok', false, 'error', 'no_session'); end if;

  select * into p from public.promos2 where code = v_code;
  if p.code is null then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
  if p.max_uses is not null and p.uses >= p.max_uses then
    return jsonb_build_object('ok', false, 'error', 'limit');
  end if;

  begin
    insert into public.promo_uses (account_id, code) values (v_id, v_code);
  exception when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'used');
  end;

  update public.promos2 set uses = uses + 1 where code = v_code;

  if p.money > 0 then
    update public.accounts
       set balance    = balance + p.money,
           state      = jsonb_set(coalesce(state, '{}'::jsonb), '{balance}',
                                  to_jsonb(balance + p.money), true),
           updated_at = now()
     where id = v_id;
  end if;

  return jsonb_build_object(
           'ok', true, 'code', v_code, 'money', p.money,
           'gift', p.gift, 'score', p.score, 'note', p.note);
end;
$$;

-- =====================================================================
-- ТОП ИГРОКОВ
-- =====================================================================
create or replace function public.sb_leaderboard(p_limit int)
returns table (place int, name text, balance numeric)
language sql security definer set search_path = public as $$
  select (row_number() over (order by a.balance desc))::int,
         coalesce(a.username, 'Игрок ' || right(a.login_id, 4)),
         a.balance
    from public.accounts a
   order by a.balance desc
   limit greatest(coalesce(p_limit, 20), 1);
$$;

-- =====================================================================
-- ДОСТУП: только эти функции, таблицы закрыты
-- =====================================================================
grant execute on function public.sb_register(text, text, jsonb)   to anon, authenticated;
grant execute on function public.sb_login(text, text)             to anon, authenticated;
grant execute on function public.sb_pull(uuid)                    to anon, authenticated;
grant execute on function public.sb_push(uuid, jsonb)             to anon, authenticated;
grant execute on function public.sb_claim_accruals(uuid)          to anon, authenticated;
grant execute on function public.sb_username_free(text)           to anon, authenticated;
grant execute on function public.sb_claim_username(uuid, text)    to anon, authenticated;
grant execute on function public.sb_redeem_promo(uuid, text)      to anon, authenticated;
grant execute on function public.sb_leaderboard(int)              to anon, authenticated;

select 'SlimBANK v2 ready' as status;
